//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int PlaceId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Facility { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Suburb { get; set; }
        public int ActivityActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
