//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string Education_Sector { get; set; }
        public string School_Type { get; set; }
        public string School_Name { get; set; }
        public string Address_Line_1 { get; set; }
        public string Suburb { get; set; }
        public string Full_Phone_No { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Secondary_language { get; set; }
    }
}
